---
- hosts: all
  become: true
  roles:
    - ups
    - docker
    - kubernetes/common

- hosts: master
  become: true
  roles:
    - kubernetes/master

- hosts: workers
  become: true
  roles:
    - kubernetes/worker

- hosts: master
  roles:
    - kubernetes/label
    - kubernetes/helm
    - helm/local-path-provisioner
    - helm/prometheus
    - helm/loki
    - helm/cert-manager
    - helm/metallb
