---
- name: Homelab Playbook - General
  hosts: all
  become: true
  roles:
    - ups
    - docker
    - kubernetes/common

- name: Homelab Playbook - Master
  hosts: master
  become: true
  roles:
    - kubernetes/master

- name: Homelab Playbook - Workers
  hosts: workers
  become: true
  roles:
    - kubernetes/worker

- name: Homelab Playbook - Setup
  hosts: master
  roles:
    - kubernetes/label
    - kubernetes/helm
    - helm/local-path-provisioner
    - helm/prometheus
    - helm/loki
    - helm/cert-manager
    - helm/metallb
    - helm/ingress
    - helm/drone
    - helm/postgresql
    - helm/mongodb
