master:
  hosts:
    master.local:
      ansible_host: 10.20.0.2
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/master/virtualbox/private_key
workers:
  hosts:
    worker-1.local:
      ansible_host: 10.20.0.3
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/worker-1/virtualbox/private_key
    worker-2.local:
      ansible_host: 10.20.0.4
      ansible_port: 22
      ansible_user: vagrant
      ansible_ssh_private_key_file: .vagrant/machines/worker-2/virtualbox/private_key
