---
- name: "Labeling worker nodes"
  command: kubectl label node {{ item }} node-role.kubernetes.io/worker=worker --overwrite
  changed_when: "'not' not in label.stdout"
  register: label
  with_items: "{{ groups['workers'] }}"
