name: ci

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run lint
        uses: ansible/ansible-lint-action@main
        with:
          targets: "playbook.yml"
          args: ""
